Parameters:
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: !Ref KeyName
      ImageId: 'ami-06b8f0fe534eceb95'
      InstanceType: 'c6g.medium'
      UserData:
        Fn::Base64: !Sub |
           #!/bin/bash 
           sudo yum update -y
           sudo yum install git -y
           git clone https://github.com/miromasat/iam-workshop.git
           sudo yum install curl -y
           curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -
           sudo yum install nodejs -y
           sudo npm install -g aws-cdk
           sudo curl -O https://bootstrap.pypa.io/get-pip.py
           python3 get-pip.py --user
           pip install boto3
           sudo yum install jq -y
           rm get-pip.py
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  Coarse:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "N"
        -
          AttributeName: "accessible"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
        -
          AttributeName: "accessible"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: "coarse"  
